routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/construccion', 'FrontController@construccion')->name('construccion');

Route::get('/', 'FrontController@index')->name('index');

Route::get('/mayoristas', 'FrontController@mayoristas')->name('mayoristas');
Route::post('/mayoristas', 'FrontController@post_mayoristas')->name('post.mayoristas');

// Route::get('/sasa', 'FrontController@sasa')->name('sasa');

Route::get('/categoria/{slug}', 'FrontController@showProductoPorCategorias')->name('categoria');

Route::get('/productos/{slug}', 'FrontController@show')->name('producto');

Route::get('/carrito', 'CartController@index')->name('carrito');
Route::post('/carrito/agregar', 'CartController@addItem')->name('addToCart');
Route::get('/carrito/item/{id}/remove', 'CartController@removeItem')->name('carrito.remove');
Route::get('/carrito/clear', 'CartController@clearCart')->name('checkout.cart.clear');

Route::get('/checkout', 'FrontController@checkout')->name('checkout');
Route::post('/postCheckout', 'FrontController@postCheckout')->name('finalizar-compra');


Route::get('/envios', 'FrontController@envios')->name('envios');
Route::get('/preguntas-frecuentes', 'FrontController@preguntasFrecuentes')->name('preguntas-frecuentes');


// Admin
Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', 'HomeController@index')->name('index');
    Route::get('optimizar', 'HomeController@optimizar')->name('optimizar');
    Route::get('fede', 'CategoriasController@index')->name('fede');

    Route::resource('categorias', 'CategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('caracteristicas', 'CaracteristicasController');
    Route::resource('esquemas', 'EsquemasController');

    Route::resource('pedidos', 'PedidosController');
    Route::get('getPedidos', 'PedidosController@getPedidos')->name('getPedidos');
    Route::resource('clientes', 'ClientesController');

    Route::get('mercadopago', 'admin\MercadoPagoController@index')->name('mercadopago');
    Route::get('crearticket', 'admin\MercadoPagoController@crearTicket')->name('mercadopago.crearticket');

});

app/Http/Controllers/PedidosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PedidosCreateRequest;
use App\Http\Requests\PedidosUpdateRequest;
use App\Repositories\PedidosRepository;
use App\Validators\PedidosValidator;
use Illuminate\Http\Request;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

/**
 * Class PedidosController.
 *
 * @package namespace App\Http\Controllers;
 */
class PedidosController extends Controller
{
    /**
     * @var PedidosRepository
     */
    protected $repository;

    /**
     * @var PedidosValidator
     */
    protected $validator;

    /**
     * PedidosController constructor.
     *
     * @param PedidosRepository $repository
     * @param PedidosValidator $validator
     */
    public function __construct(PedidosRepository $repository, PedidosValidator $validator)
    {
        $this->repository = $repository;
        $this->validator = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $pedidos = $this->repository->with('cliente')->all(['id', 'estado', 'pedido_id', 'total', 'created_at', 'cliente_id', 'carrito']);
        // dd($pedidos);
        return view('admin.pedidos.index', compact('pedidos'));
    }
    public function getPedidos()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $pedidos = $this->repository->with('cliente')->all(['id', 'pedido_id', 'total', 'created_at', 'cliente_id']);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $pedidos,
            ]);
        }

        return view('admin.pedidos.index', compact('pedidos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  PedidosCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(PedidosCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $pedido = $this->repository->create($request->all());

            $response = [
                'message' => 'Pedidos created.',
                'data' => $pedido->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag(),
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pedido = $this->repository->with(['cliente'])->findByField('pedido_id', $id)->first();
        // dd($pedido);
        if (request()->wantsJson()) {

            return response()->json([
                'data' => $pedido,
            ]);
        }

        return view('admin.pedidos.show', compact('pedido'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pedido = $this->repository->find($id);

        return view('admin.pedidos.edit', compact('pedido'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  PedidosUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(PedidosUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $pedido = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Pedidos updated.',
                'data' => $pedido->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag(),
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Pedidos deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Pedidos deleted.');
    }
}

resources/views/admin/pedidos/create.blade.php
@extends('admin.includes.app')

@section('contenido')
<!-- Main contenido -->
<section class="contenido">
    @include('admin.includes.mensajero')
    <div class="card">
        <form action="{{ route('admin.categorias.store') }}" method="post" class="form" enctype="multipart/form-data">
            <div class="card-body row">
                {{ csrf_field() }}
                <div class="col-md-8">
                    <h2>Categoria Nueva</h2>

                    <div class="form-group">
                        <label for="nombre">Nombre <span class="text-danger">*</span></label>
                        <input type="text" name="nombre" id="nombre" placeholder="" class="form-control"
                            value="{{ old('nombre') }}">
                    </div>

                    <div class="form-group">
                        <label for="descripcion">Descripcion </label>
                        <textarea class="form-control" name="descripcion" id="descripcion" rows="5"
                            placeholder="Descripcion">{{ old('descripcion') }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="parent"> Parent_ID <span class="text-danger">*</span></label>
                        <input type="text" name="parent" id="parent" placeholder="" class="form-control" value="{{ old('parent_id') }}">
                    </div>
                    <div class="form-group">
                        <label for="peso"> Peso <span class="text-danger">*</span></label>
                        <input type="text" name="peso" id="peso" placeholder="0" class="form-control" value="{{ old('peso') }}">
                    </div>

                </div>
                <div class="col-md-4">
                    <h2>Imagenes</h2>
                    <div class="form-group">
                        <label for="portada">Portada </label>
                        <input type="file" name="portada" id="portada" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="image">Galeria</label>
                        <input type="file" name="image[]" id="image" class="form-control" multiple>
                        <small class="text-muted">Podes elegir mas de una imagen</small>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div class="btn-group">
                    <a href="{{ route('admin.categorias.index') }}" class="btn btn-default">Atras</a>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            </div>
        </form>
    </div>
    <!-- /.card -->

</section>
<!-- /.contenido -->
@endsection

resources/views/admin/pedidos/edit.blade.php
@extends('admin.includes.app')

@section('contenido')
<!-- Main contenido -->
<section class="contenido">
    @include('admin.includes.mensajero')
    <div class="card">
        <div class="card-header">
            <h2 class="d-inline">{{ ucfirst($categoria->nombre) }}</h2>

        </div>
        <form action="{{ route('admin.categorias.update', $categoria->id) }}" method="post" id="form" class="form"
            enctype="multipart/form-data">
            <div class="card-body row">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">
                <div class="col-12">
                    @include('admin.includes.imagenes', ['item' => $categoria])
                    <hr>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="nombre">Nombre <span class="text-danger">*</span></label>
                        <input type="text" name="nombre" id="nombre" placeholder="xxxxx" class="form-control"
                            value="{!! $categoria->nombre !!}">
                    </div>
                    <div class="form-group">
                        <label for="slug">slug <span class="text-danger">*</span></label>
                        <input type="text" name="slug" id="slug" placeholder="xxxxx" class="form-control"
                            value="{!! $categoria->slug !!}">
                    </div>

                    <div class="form-group">
                        <label for="descripcion">Descripcion </label>
                        <textarea class="form-control" name="descripcion" id="descripcion" rows="5"
                            placeholder="Descripcion">{!! $categoria->descripcion !!}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="parent">Parent <span class="text-danger">*</span></label>
                        <input type="text" name="parent" id="parent" placeholder="parent" class="form-control"
                            value="{!! $categoria->parent !!}">
                    </div>

                    <div class="form-group">
                        @include('admin.includes.estado',[
                        'id' => $categoria->id,
                        'estado' => $categoria->estado,
                        'ruta' => 'admin.categorias.update',
                        'update' => false
                        ])
                    </div>

                </div>
                <div class="col-md-4">

                    <h2>Imagenes</h2>
                    {{-- <div class="form-group">
                            @foreach($images as $image)
                            <div class="col-md-3">
                                <div class="row">
                                    <img src="{{ asset("storage/$image->src") }}" alt="" class="img-responsive img-thumbnail"> <br /> <br>
                                    <a onclick="return confirm('Are you sure?')" href="{{ route('product.remove.thumb', ['src' => $image->src]) }}" class="btn btn-danger btn-sm btn-block">Remove?</a><br />
                                </div>
                            </div>
                            @endforeach
                        </div>  --}}



                    <div class="form-group">
                        <label for="portada_file">Portada </label>
                        <input type="file" name="portada_file" id="portada_file" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="image">Galeria</label>
                        <input type="file" name="image[]" id="image" class="form-control" multiple>
                        <small class="text-muted">Podes elegir mas de una imagen</small>
                    </div>

                </div>
            </div>
        </form>
        <div class="card-footer">
            <div class="btn-group">
                <a href="{{ route('admin.categorias.index') }}" class="btn btn-default">Atras</a>
                <button type="submit" onclick="event.preventDefault(); document.getElementById('form').submit();"class="btn btn-primary">Guardar Cambios</button>
            </div>
        </div>

    </div>
    <!-- /.card -->

</section>
<!-- /.contenido -->
@endsection

resources/views/admin/pedidos/index.blade.php
@extends('admin.includes.app')

@section('contenido')
<div class="row">

    <div class="col">
        <div class="card">
            <div class="card-header">
                <ul class="nav">
                    <li class="nav-item pt-2">
                        <p>Pedidos</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle" href="#" role="button" id="Estado" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            Estado
                        </a>
                        <div class="dropdown-menu" aria-labelledby="Estado">
                            <a class="dropdown-item"
                                href="
                                                            {{ route('admin.pedidos.index', ['estado' => 'pago']) }}">Pagados</a>
                            <a class="dropdown-item"
                                href="{{ route('admin.pedidos.index', ['estado' => 'sinpagar']) }}">Sin
                                pagar</a>
                            <a class="dropdown-item"
                                href="{{ route('admin.pedidos.index', ['estado' => 'enviado']) }}">Enviado</a>
                        </div>

                    </li>
                </ul>
            </div>

            <div class="card-body">
                <pedidos-component></pedidos-component>
            </div>
        </div>
    </div>
    <div class="d-none d-md-block col-md-4">
        <div class="">
            <ul class="list-group">
                <li class="list-group-item"></li>
                <li class="list-group-item"></li>
                <li class="list-group-item"></li>
                <li class="list-group-item"></li>
            </ul>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script src="{{ asset('js/admin/pedidos.js') }}"></script>
@endpush

resources/views/admin/pedidos/show.blade.php
@extends('admin.includes.app')

@section('contenido')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">  <a href="{{ url()->previous() }}" class="btn-link mr-3">Atras</a> Pedido {{$pedido->id}}</div>
            <div class="card-body">
                <pedido-component :pedido="{{$pedido}}"></pedido-component>
            </div>
        </div>

    </div>
</div>
@endsection
@push('scripts')
    <script src="{{ asset('js/admin/pedidos.js') }}"></script>
@endpush