routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/construccion', 'FrontController@construccion')->name('construccion');

Route::get('/', 'FrontController@index')->name('index');

Route::get('/mayoristas', 'FrontController@mayoristas')->name('mayoristas');
Route::post('/mayoristas', 'FrontController@post_mayoristas')->name('post.mayoristas');

// Route::get('/sasa', 'FrontController@sasa')->name('sasa');

Route::get('/categoria/{slug}', 'FrontController@showProductoPorCategorias')->name('categoria');

Route::get('/productos/{slug}', 'FrontController@show')->name('producto');

Route::get('/carrito', 'CartController@index')->name('carrito');
Route::post('/carrito/agregar', 'CartController@addItem')->name('addToCart');
Route::get('/carrito/item/{id}/remove', 'CartController@removeItem')->name('carrito.remove');
Route::get('/carrito/clear', 'CartController@clearCart')->name('checkout.cart.clear');

Route::get('/checkout', 'FrontController@checkout')->name('checkout');
Route::post('/postCheckout', 'FrontController@postCheckout')->name('finalizar-compra');


Route::get('/envios', 'FrontController@envios')->name('envios');
Route::get('/preguntas-frecuentes', 'FrontController@preguntasFrecuentes')->name('preguntas-frecuentes');


// Admin
Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', 'HomeController@index')->name('index');
    Route::get('optimizar', 'HomeController@optimizar')->name('optimizar');
    Route::get('fede', 'CategoriasController@index')->name('fede');

    Route::resource('categorias', 'CategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('caracteristicas', 'CaracteristicasController');
    Route::resource('esquemas', 'EsquemasController');

    Route::resource('pedidos', 'PedidosController');
    Route::get('getPedidos', 'PedidosController@getPedidos')->name('getPedidos');
    Route::resource('clientes', 'ClientesController');

    Route::get('mercadopago', 'admin\MercadoPagoController@index')->name('mercadopago');
    Route::get('crearticket', 'admin\MercadoPagoController@crearTicket')->name('mercadopago.crearticket');

});

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\ProductoCreateRequest;
use App\Http\Requests\ProductoUpdateRequest;
use App\Repositories\ProductoRepository;
use App\Validators\ProductoValidator;
use App\Repositories\CategoriasRepository;
use App\Helpers\ImageHelper;

/**
 * Class ProductosController.
 *
 * @package namespace App\Http\Controllers;
 */
class ProductosController extends Controller
{
    /**
     * @var ProductoRepository
     */
    protected $repository;
    protected $categoriasRepository;

    /**
     * @var ProductoValidator
     */
    protected $validator;

    /**
     * ProductosController constructor.
     *
     * @param ProductoRepository $repository
     * @param ProductoValidator $validator
     */
    public function __construct(
        ProductoRepository $repository,
        ProductoValidator $validator,
        CategoriasRepository $categoriasRepository
        )
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->categoriasRepo  = $categoriasRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $categorias = $this->categoriasRepo->all();

        // dd($request);
        if($categoria = $request->query('categoria')){
            $categoria = $this->categoriasRepo->where('id', $categoria)->first();
            $productos = $categoria->productos;
            foreach ($categoria->subcategorias as $subcate) {
                $productos = $productos->concat($subcate->productos);
            }
            $productos = collect($productos);
            return view('admin.productos.list', compact('productos', 'categorias'));
        }
        $productos = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $productos,
            ]);
        }

        return view('admin.productos.list', compact('productos', 'categorias'));
    }

    public function create()
    {
        $categorias = $this->categoriasRepo->lista('id', 'asc');
        return view('admin.productos.create',[
            'categorias' => $categorias
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ProductoCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(ProductoCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $input = $request->all();

            if ($request->hasFile('portada')) {
                $imageHelper = new ImageHelper();
                $photo = $imageHelper->upload($request->portada);

                if (!$photo['error']) {

                    $input['portada'] = $photo['imagen'];
                } else {
                    $input['portada'] = 'placeholder.jpg';
                }
            }

            $producto = $this->repository->create($input);

            if ($request->has('categoria')) {
                $producto->categorias()->sync([$request->input('categoria')]);
            } else {
                $this->repository->detachCategories();
            }



            $response = [
                'message' => 'Producto created.',
                'data'    => $producto->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            // return redirect()->route('admin.index', [$producto])->with('message', $response['message']);

            return redirect()->back()->with('message', $response['message']);


        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $producto = $this->repository->with('esquemas')->find($id);


        if (request()->wantsJson()) {

            return response()->json([
                'data' => $producto,
            ]);
        }

        return view('admin.productos.show', compact('producto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = $this->repository->find($id);

        $categorias = $this->categoriasRepo->lista('id', 'asc');

        return view('admin.productos.edit', compact('producto', 'categorias'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ProductoUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(ProductoUpdateRequest $request, $id)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            if ($request->hasFile('portada_file')) {
                $imageHelper = new ImageHelper();
                $photo = $imageHelper->upload($request->portada_file);

                if (!$photo['error']) {
                    $request->merge(['portada' => $photo['imagen']]);
                } else {
                    $request->merge(['portada' => '']);
                }
           }

            $producto = $this->repository->update($request->all(), $id);

            if ($request->has('categoria')) {

                $producto->categorias()->sync([$request->input('categoria')]);
            }


            $response = [
                'message' => 'Producto updated.',
                'data'    => $producto->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $producto = $this->repository->find($id);
        $producto->categorias()->sync([]);
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Producto deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Producto deleted.');
    }


}

resources/views/admin/productos/create.blade.php
@extends('admin.includes.app')

@section('contenido')
<!-- Main contenido -->
<section class="contenido">
    @include('admin.includes.mensajero')
    <div class="card">
        <form action="{{ route('admin.productos.store') }}" method="post" class="form" enctype="multipart/form-data">
            <div class="card-body row">
                {{ csrf_field() }}
                <div class="col-md-8">
                    <h2>Producto Nuevo</h2>

                    <div class="form-group">
                        <label for="nombre">Nombre <span class="text-danger">*</span></label>
                        <input type="text" name="nombre" id="nombre" placeholder="" class="form-control"
                            value="{{ old('nombre') }}">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="precio">Precio <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                <input type="text" name="precio" id="precio" placeholder="" class="form-control"
                                    value="{{ old('precio') }}">
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="precio">Precio promocion <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">$</span>
                                </div>
                                <input type="text" name="precio_promocion" id="precio" placeholder="" class="form-control"
                                    value="{{ old('precio') }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripcion </label>
                        <input type="hidden" class="form-control" name="descripcion"></input>
                        <div class="form-control " id="descripcion"></div>
                    </div>

                    <div class="form-group">
                        <label for="categoria">Categoria </label>

                        <select class="custom-select" name="categoria">
                        <option selected>Categoria</option>
                        @if(!$categorias->isEmpty())
                            @foreach ($categorias as $categoria)
                                <option value="{{$categoria->id}}">{{$categoria->nombre}}</option>
                            @endforeach
                        @endif
                    </select>

                    </div>

                    {{-- @include('admin.shared.status-select', ['status' => 0])
                    @include('admin.shared.attribute-select', [compact('default_weight')]) --}}
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">

                    <a href="{{ route('admin.productos.index') }}" class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-primary">GUARDAR</button>

            </div>
        </form>
    </div>
    <!-- /.card -->

</section>
<!-- /.contenido -->
@endsection
@push('scripts')
<!-- Main Quill library -->
<script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>

<!-- Theme included stylesheets -->
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
<script>
var quill = new Quill('#descripcion', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
    //   ['image', 'code-block'],
      [{ list: 'ordered' }, { list: 'bullet' }]
    ]
  },
  theme: 'bubble'  // or 'bubble'
});
var form = document.querySelector('.form');
console.log(form);
form.onsubmit = function(e) {
    e.preventDefault();
  var descripcion = document.querySelector('input[name=descripcion]');
  descripcion.value = quill.root.innerHTML.trim();
  form.submit();

};
</script>
@endpush

resources/views/admin/productos/edit-modal.blade.php
        <form action="{{ route('admin.productos.update', $producto->id) }}" method="post" class="form"
            enctype="multipart/form-data">
            <div class="row">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">
                <div class="col-12">
                <div class="form-group">
                        @include('admin.includes.estado',[
                        'id' => $producto->id,
                        'estado' => $producto->estado,
                        'ruta' => 'admin.productos.update',
                        'update' => false
                        ])
                    </div>
                    </div>
                <div class="col-12">
                    @include('admin.includes.imagenes', ['item' => $producto])
                    <hr>
                </div>
                <div class="col-md-8">

                    <div class="form-group">
                        <label for="nombre">Nombre <span class="text-danger">*</span></label>
                        <input type="text" name="nombre" id="nombre" placeholder="" class="form-control"
                            value="{!! $producto->nombre !!}">
                    </div>

                    <div class="form-group">
                        <label for="descripcion">Descripcion </label>
                        <textarea class="form-control" name="descripcion" id="descripcion" rows="5"
                            placeholder="Descripcion">{!! $producto->descripcion !!}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="stock_publico">Stock_publico <span class="text-danger">*</span></label>
                        <input type="text" name="stock_publico" id="stock_publico" placeholder="stock_publico"
                            class="form-control" value="{!! $producto->stock_publico !!}">
                    </div>

                    <div class="form-group">
                        <label for="precio">Precio <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">$</span>
                            </div>
                            <input type="text" name="precio" id="precio" placeholder="precio" class="form-control"
                                value="{!! $producto->precio !!}">
                        </div>
                    </div>

                    

                    {{-- @include('admin.shared.status-select', ['status' => 0]) --}}

                </div>

                <div class="col-md-4">

                    <h2>Categoria</h2>

                    <div class="form-group">
                        <select class="custom-select" name="categoria">
                            <option selected>Categoria</option>
                            @if(!$categorias->isEmpty())
                                @foreach ($categorias as $categoria)
                                    <option
                                    value="{{$categoria->id}}"
                                    @if(
                                    isset($producto->categorias)
                                    && $producto->categorias->contains($categoria->id))
                                    selected="selected"
                                    @endif
                                        >{{$categoria->nombre}}</option>
                                @endforeach
                            @endif
                        </select>
                    </div>

                    <hr>

                    <h2>Imagenes</h2>

                    {{--
                        <div class="form-group">
                            @foreach($images as $image)
                            <div class="col-md-3">
                                <div class="row">
                                    <img src="{{ asset("storage/$image->src") }}" alt="" class="img-responsive img-thumbnail"> <br /> <br>
                                    <a onclick="return confirm('Are you sure?')" href="{{ route('product.remove.thumb', ['src' => $image->src]) }}" class="btn btn-danger btn-sm btn-block">Remove?</a><br />
                                </div>
                            </div>
                            @endforeach
                        div>
                     --}}

                    <div class="form-group">
                        <label for="portada">Portada </label>
                        <input type="file" name="portada_file" id="portada" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="image">Galeria</label>
                        <input type="file" name="image[]" id="image" class="form-control" multiple>
                        <small class="text-muted">Podes elegir mas de una imagen</small>
                    </div>

                </div>

            </div><!-- /.card-body -->

            <div class="card-footer">
                <div class="btn-group">
                    <a href="{{ route('admin.productos.index') }}" class="btn btn-default">Atras</a>
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                </div>
            </div>
        </form>
    </div><!-- /.card -->


</section>

resources/views/admin/productos/edit.blade.php
@extends('admin.includes.app')

@section('contenido')
<!-- Main contenido -->
<section class="contenido">
    @include('admin.includes.mensajero')
    <div class="card">

        <div class="card-header">

            <h4 class="d-inline">{{ ucfirst($producto->nombre) }}</h4>

        </div>
        <form action="{{ route('admin.productos.update', $producto->id) }}" method="post" class="form"
            enctype="multipart/form-data">
            <div class="card-body row">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">
                <div class="col-12">
                    @include('admin.includes.imagenes', ['item' => $producto])
                    <hr>

                </div>
                <div class="col-md-8">

                    <div class="form-group">
                        <label for="nombre">Nombre <span class="text-danger">*</span></label>
                        <input type="text" name="nombre" id="nombre" placeholder="" class="form-control"
                            value="{!! $producto->nombre !!}">
                    </div>

                    <div class="form-group">


                        <label for="descripcion">Descripcion </label>
                        <input type="hidden" class="form-control" name="descripcion"></input>
                        <div class="form-control " id="descripcion">{!! $producto->descripcion !!}</div>
                    </div>

                    <div class="form-group">
                        <label for="stock_publico">Stock_publico <span class="text-danger">*</span></label>
                        <input type="text" name="stock_publico" id="stock_publico" placeholder="stock_publico"
                            class="form-control" value="{!! $producto->stock_publico !!}">
                    </div>

                    <div class="form-group">
                        <label for="precio">Precio <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">$</span>
                            </div>
                            <input type="text" name="precio" id="precio" placeholder="precio" class="form-control"
                                value="{!! $producto->precio !!}">
                        </div>
                    </div>

                    <div class="form-group">
                        @include('admin.includes.estado',[
                        'id' => $producto->id,
                        'estado' => $producto->estado,
                        'ruta' => 'admin.productos.update',
                        'update' => false
                        ])
                    </div>

                    <label for="destacado">Destacado en portada </label>
                    <select name="destacado" id="" class="form-control">
                        <option value="1" @if($producto->destacado) selected="selected" @endif>En portada</option>
                        <option value="0" @if(!$producto->destacado) selected="selected" @endif>Sin destacar</option>
                    </select>

                    {{-- @include('admin.shared.status-select', ['status' => 0]) --}}

                </div>

                <div class="col-md-4">

                    <h2>Categoria</h2>

                    <div class="form-group">
                        <select class="custom-select" name="categoria">
                            <option selected>Categoria</option>
                            @if(!$categorias->isEmpty())
                                @foreach ($categorias as $categoria)
                                    <option
                                    value="{{$categoria->id}}"
                                    @if(
                                    isset($producto->categorias)
                                    && $producto->categorias->contains($categoria->id))
                                    selected="selected"
                                    @endif
                                        >{{$categoria->nombre}}</option>
                                @endforeach
                            @endif
                        </select>
                    </div>

                    <hr>

                    <h2>Imagenes</h2>

                    {{--
                        <div class="form-group">
                            @foreach($images as $image)
                            <div class="col-md-3">
                                <div class="row">
                                    <img src="{{ asset("storage/$image->src") }}" alt="" class="img-responsive img-thumbnail"> <br /> <br>
                                    <a onclick="return confirm('Are you sure?')" href="{{ route('product.remove.thumb', ['src' => $image->src]) }}" class="btn btn-danger btn-sm btn-block">Remove?</a><br />
                                </div>
                            </div>
                            @endforeach
                        div>
                     --}}

                    <div class="form-group">
                        <label for="portada">Portada </label>
                        <input type="file" name="portada_file" id="portada" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="image">Galeria</label>
                        <input type="file" name="image[]" id="image" class="form-control" multiple>
                        <small class="text-muted">Podes elegir mas de una imagen</small>
                    </div>

                </div>

            </div><!-- /.card-body -->

            <div class="card-footer">
                <div class="btn-group">
                    <a href="{{ route('admin.productos.index') }}" class="btn btn-default">Atras</a>
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                </div>
            </div>
        </form>
    </div><!-- /.card -->


</section>
<!-- /.contenido -->
@endsection

@push('scripts')
<!-- Main Quill library -->
<script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>

<!-- Theme included stylesheets -->
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
<script>
var quill = new Quill('#descripcion', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
    //   ['image', 'code-block'],
      [{ list: 'ordered' }, { list: 'bullet' }]
    ]
  },
  theme: 'bubble'  // or 'bubble'
});
var form = document.querySelector('.form');
console.log(form);
form.onsubmit = function(e) {
    e.preventDefault();
  var descripcion = document.querySelector('input[name=descripcion]');
  descripcion.value = quill.root.innerHTML.trim();
  form.submit();

};
</script>
@endpush

resources/views/admin/productos/list.blade.php
@extends('admin.includes.app')

@section('contenido')
<!-- Main contenido -->
<section class="contenido">

    <div class="card">
        <div class="card-header">
            <ul class="nav">

                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" role="button" id="categorias" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Categorias
                    </a>
                    <div class="dropdown-menu" aria-labelledby="categorias">
                        @foreach ($categorias as $item)
                        <a class="dropdown-item"
                            href="{{ route('admin.productos.index', ['categoria' => $item->id]) }}">{{$item->nombre}}</a>
                        @endforeach
                    </div>
                </li>

                <li class="nav-item ">
                    <a class="nav-link " href="{{route('admin.categorias.index')}}">Editar Categorias</a>
                </li>

                <li class="nav-item ml-auto">
                    <a class="nav-link btn btn-sm rounded btn-outline-primary"
                        href="{{route('admin.productos.create')}}">CREAR PRODUCTO</a>
                </li>
            </ul>
            {{--
            <div class="row">
                <div class="col">
                    <a href="{{ route('admin.productos.index', ['orderBy' => 'created_at']) }}">Mas
            nuevos</a>
        </div>
        <div class="col text-right">
            <a href="{{ route('admin.productos.create') }}" class="btn btn-success">Nuevo</a>
        </div>
    </div> --}}
    {{-- Filtros y demas --}}
    </div>
    <div class="card-body">
        @if(!$productos->isEmpty())

        <table class="table">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Nombre</td>
                    <td>Precio</td>
                    <td>Estado</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($productos as $producto)
                <tr>
                    <td>{{ $producto->id }}</td>
                    <td>
                        <a href="{{ route('admin.productos.show', $producto->id) }}">{{ $producto->nombre }}</a>
                    </td>
                    <td>{{ $producto->precio }}</td>
                    <td>
                        @include('admin.includes.estado',[
                        'id' => $producto->id,
                        'estado' => $producto->estado,
                        'ruta' => 'admin.productos.update',
                        'update' => true
                        ])
                    </td>
                    <td>
                        <form action="{{ route('admin.productos.destroy', $producto->id) }}" method="post"
                            class="form-horizontal">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="delete">
                            <div class="btn-group">
                                <a href="{{ route('admin.productos.edit', $producto->id) }}"
                                    class="btn btn-outline-dark btn-sm">
                                    <i class="fa fa-edit"></i> Editar</a>
                                <button onclick="return confirm('Seguro?')" type="submit"
                                    class="btn btn-outline-dark btn-sm">
                                    <i class="fa fa-times"></i> Eliminar</button>
                            </div>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        @else


        <div class="row justify-contenido-center">
            <div class="col text-center py-5">
                <h2>No hay productos cargados</h2>
            </div>
        </div>

        @endif

    </div>
    <div class="card-footer"></div>
    </div>



</section>



@endsection