routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/construccion', 'FrontController@construccion')->name('construccion');

Route::get('/', 'FrontController@index')->name('index');

Route::get('/mayoristas', 'FrontController@mayoristas')->name('mayoristas');
Route::post('/mayoristas', 'FrontController@post_mayoristas')->name('post.mayoristas');

// Route::get('/sasa', 'FrontController@sasa')->name('sasa');

Route::get('/categoria/{slug}', 'FrontController@showProductoPorCategorias')->name('categoria');

Route::get('/productos/{slug}', 'FrontController@show')->name('producto');

Route::get('/carrito', 'CartController@index')->name('carrito');
Route::post('/carrito/agregar', 'CartController@addItem')->name('addToCart');
Route::get('/carrito/item/{id}/remove', 'CartController@removeItem')->name('carrito.remove');
Route::get('/carrito/clear', 'CartController@clearCart')->name('checkout.cart.clear');

Route::get('/checkout', 'FrontController@checkout')->name('checkout');
Route::post('/postCheckout', 'FrontController@postCheckout')->name('finalizar-compra');


Route::get('/envios', 'FrontController@envios')->name('envios');
Route::get('/preguntas-frecuentes', 'FrontController@preguntasFrecuentes')->name('preguntas-frecuentes');


// Admin
Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {

    Route::get('/', 'HomeController@index')->name('index');
    Route::get('optimizar', 'HomeController@optimizar')->name('optimizar');
    Route::get('fede', 'CategoriasController@index')->name('fede');

    Route::resource('categorias', 'CategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('caracteristicas', 'CaracteristicasController');
    Route::resource('esquemas', 'EsquemasController');

    Route::resource('pedidos', 'PedidosController');
    Route::get('getPedidos', 'PedidosController@getPedidos')->name('getPedidos');
    Route::resource('clientes', 'ClientesController');

    Route::get('mercadopago', 'admin\MercadoPagoController@index')->name('mercadopago');
    Route::get('crearticket', 'admin\MercadoPagoController@crearTicket')->name('mercadopago.crearticket');

});

resources/views/admin/includes/app.blade.php
@extends('layouts.app')

@section('subnav')
    <div class="container mt-1">
        <div class="row">
            <div class="col">
                <ul class="nav nav-pills ">
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin')) ? 'active' : '' }}"
                            href="{{route('admin.index')}}"><i class="bi bi-house-fill"></i> Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/pedidos*')) ? 'active' : '' }}"
                            href="{{route('admin.pedidos.index')}}">Pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/productos*')) ? 'active' : '' }}"
                            href="{{route('admin.productos.index')}}">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/sellos*')) ? 'active' : '' }}" href="#">Sellos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('admin/categorias*')) ? 'active' : '' }}"
                            href="{{route('admin.categorias.index')}}">Categorias</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection


@section('content')
   <div class="container mt-4">
       @yield('contenido')
   </div>
@endsection

resources/views/admin/includes/categorias.blade.php
<ul class="checkbox-list">
    @foreach($categorias as $categoria)
    <li>
        <div class="checkbox">
            <label>
                <input type="checkbox" @if(isset($selectedIds) && in_array($categoria->id,
                $selectedIds))checked="checked" @endif
                name="categorias[]"
                value="{{ $categoria->id }}">
                {{ $categoria->nombre }}
            </label>
        </div>
    </li>
    @if($categoria->children->count() >= 1)
    @include('admin.includes.categorias', ['categorias' => $categoria->children, 'selectedIds' => $selectedIds])
    @endif
    @endforeach
</ul>

resources/views/admin/includes/estado.blade.php
@if(isset($estado))
    @if ($update)
    <form action="{{ route($ruta, $id) }}" method="post" class="form-horizontal">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="put">
        @if($estado == 1)
            <input type="hidden" name="estado" value="0">
            <span style="display: none; visibility: hidden">1</span>
            <button type="submit" class="btn btn-outline-success btn-sm">
                <i class="fa fa-check"></i> Publicado
            </button>
            @else
            <input type="hidden" name="estado" value="1">
            <span style="display: none; visibility: hidden">0</span>
            <button type="submit" class="btn btn-outline-danger btn-sm">
                <i class="fa fa-times"></i> Borrador
            </button>
        @endif

        </form>


        @else
        <label for="estado">Estado</label>
        <select name="estado" id="" class="form-control">
            <option value="1" @if($estado) selected="selected" @endif>Publicado</option>
            <option value="0" @if(!$estado) selected="selected" @endif>Borrador</option>
        </select>


    @endif



@endif

resources/views/admin/includes/imagenes.blade.php
<div class="row galeria d-flex" >
    <div class="col">
        {{-- if - Tengo portada o imagenes --}}
        @if($item->portada)

            <img src="{{asset('imagenes/thumbs/'.$item->portada)}}" alt="..." class="img-thumbnail lazyload">
            <div class="thumb-links mt-2">
                <a href=""> <i class="fa fa-trash mr-2"></i>Eliminar</a>
            </div>

        @endif

    </div>

</div>

resources/views/admin/includes/mensajero.blade.php
@if($errors->all())
@foreach($errors->all() as $message)
<div class="box no-border">
    <div class="box-tools">
        <p class="alert alert-warning alert-dismissible">
            {{ $message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        </p>
    </div>
</div>
@endforeach

@elseif(session()->has('message'))
<div class="box no-border">
    <div class="box-tools">
        <p class="alert alert-success alert-dismissible">
            {{ session()->get('message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        </p>
    </div>
</div>
@elseif(session()->has('error'))
<div class="box no-border">
    <div class="box-tools">
        <p class="alert alert-danger alert-dismissible">
            {{ session()->get('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        </p>
    </div>
</div>
@endif